// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmIllDkhgFLwUid5Kb3ddSF6AfIUSHC08',
    appId: '1:360956921475:web:4d586a78a20609791bfdb6',
    messagingSenderId: '360956921475',
    projectId: 'zaksocial-a4825',
    authDomain: 'zaksocial-a4825.firebaseapp.com',
    storageBucket: 'zaksocial-a4825.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByCoGtrZHVAdQiz6Pq7jGTL9V5sHkEuNk',
    appId: '1:360956921475:android:dd6711cd3fbf92521bfdb6',
    messagingSenderId: '360956921475',
    projectId: 'zaksocial-a4825',
    storageBucket: 'zaksocial-a4825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1FLDLfjcAjEFFfjY_PojJCJ2-BzvPqQ',
    appId: '1:360956921475:ios:d0d5023c0efcd6ea1bfdb6',
    messagingSenderId: '360956921475',
    projectId: 'zaksocial-a4825',
    storageBucket: 'zaksocial-a4825.appspot.com',
    iosBundleId: 'com.example.minimalSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf1FLDLfjcAjEFFfjY_PojJCJ2-BzvPqQ',
    appId: '1:360956921475:ios:da6d90505b36ac1d1bfdb6',
    messagingSenderId: '360956921475',
    projectId: 'zaksocial-a4825',
    storageBucket: 'zaksocial-a4825.appspot.com',
    iosBundleId: 'com.example.minimalSocialMediaApp.RunnerTests',
  );
}
